name: Deploy React App to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Force install npm v10.8.2
        run: |
          npm install -g npm@10.8.2
          npm -v  # log version

      - name: Install dependencies
        run: npm install --force

      - name: Build React App
        run: npm run build --force

      - name: Save EC2 private key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy with rsync via SSH key
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./dist/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}
